study_app/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
    path("math", views.math, name="math"),
    path("math/<int:id>", views.study_math, name="study_math"),
    path("physics", views.physics, name="physics"),
    path("physics/<int:id>", views.study_physics, name="study_physics"),
    path("chemistry", views.chemistry, name="chemistry"),
    path("chemistry/<int:id>", views.study_chemistry, name="study_chemistry"),
    path("comp-sci", views.compsci, name="compsci"),
    path("comp-sci/<int:id>", views.study_compsci, name="study_compsci"),
    path("feedback", views.feedback, name="feedback"),
    path("add-feedback", views.add_feedback, name="add_feedback"),
    path("feedback/<int:id>", views.feedback_delete, name="feedback_delete"),
    path("game", views.game, name="game"),
    path("test/<subject>/<unit>", views.test, name="test"),
    path("test/<subject>/<unit>/check-answer", views.test_check, name="test_check"),
    path("test/<subject>/<unit>/show-answer", views.show_answer, name="show_answer"),
    path("testing", views.testing, name="testing")
]

study_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("study_app.urls")),
    path("user/", include("user.urls"))
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path("login/", views.login_user, name="login_user"),
    path("logout/", views.logout_user, name="logout_user"),
    path("register/", views.register, name="register")
]

study_app/forms.py
from django import forms
from .models import Feedback, MathMain, PhysicsMain, ChemMain, CompSciMain, MathUnit, MathSubUnit, PhysicsUnit, \
    PhysicsSubUnit, ChemUnit, ChemSubUnit, CompSciUnit, CompSciSubUnit, MultipleChoiceQuiz, MultipleChoiceQuestion, \
    MultipleChoiceChoice

class MainsForms(forms.Form):
    title = forms.CharField(max_length=250)
    image = forms.ImageField()


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ["feedback"]
        labels = {"feedback": ""}
        widgets = {'feedback': forms.Textarea(attrs={'rows': 1})}


class MathMainForm(forms.ModelForm):
    class Meta:
        model = MathMain
        fields = ["title", "image"]


class MathUnitForm(forms.ModelForm):
    class Meta:
        model = MathUnit
        fields = ["title"]


class MathSubUnitForm(forms.ModelForm):
    class Meta:
        model = MathSubUnit
        fields = ["title", "description", "unit"]
    image = forms.ImageField(required=False)


class PhysicsMainForm(forms.ModelForm):
    class Meta:
        model = PhysicsMain
        fields = ["title", "image"]


class PhysicsUnitForm(forms.ModelForm):
    class Meta:
        model = PhysicsUnit
        fields = ["title"]


class PhysicsSubUnitForm(forms.ModelForm):
    class Meta:
        model = PhysicsSubUnit
        fields = ["title", "description", "unit"]
    image = forms.ImageField(required=False)


class ChemMainForm(forms.ModelForm):
    class Meta:
        model = ChemMain
        fields = ["title", "image"]


class ChemUnitForm(forms.ModelForm):
    class Meta:
        model = ChemUnit
        fields = ["title"]


class ChemSubUnitForm(forms.ModelForm):
    class Meta:
        model = ChemSubUnit
        fields = ["title", "description", "unit"]
    image = forms.ImageField(required=False)


class CompSciMainForm(forms.ModelForm):
    class Meta:
        model = CompSciMain
        fields = ["title", "image"]


class CompSciUnitForm(forms.ModelForm):
    class Meta:
        model = CompSciUnit
        fields = ["title"]


class CompSciSubUnitForm(forms.ModelForm):
    class Meta:
        model = CompSciSubUnit
        fields = ["title", "description", "unit"]
    image = forms.ImageField(required=False)


class MultipleChoiceQuizForm(forms.ModelForm):
    class Meta:
        model = MultipleChoiceQuiz
        fields = ["unit", "number_of_questions", "required_score_to_pass"]


class MultipleChoiceQuestionForm(forms.ModelForm):
    class Meta:
        model = MultipleChoiceQuestion
        fields = ["quiz", "title"]
    image = forms.ImageField(label="solution")


class MultipleChoiceChoiceForm(forms.ModelForm):
    class Meta:
        model = MultipleChoiceChoice
        fields = ["question", "choice", "correct"]

study_app/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from .models import Feedback, MathMain, PhysicsMain, ChemMain, CompSciMain, MathUnit, MathSubUnit, \
    PhysicsUnit, PhysicsSubUnit, ChemUnit, ChemSubUnit, CompSciUnit, CompSciSubUnit, MultipleChoiceQuestion, \
    MultipleChoiceQuiz, MultipleChoiceChoice
from .forms import FeedbackForm, MathUnitForm, MathSubUnitForm, PhysicsUnitForm, PhysicsSubUnitForm, ChemUnitForm, \
    ChemSubUnitForm, CompSciSubUnitForm, CompSciUnitForm, MultipleChoiceQuizForm, MultipleChoiceQuestionForm, \
    MultipleChoiceChoiceForm, MainsForms
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import base64

import json, random

# Create your views here.
def home(request):
    math_grades = MathMain.objects.all().order_by('date_added')
    physics_grades = PhysicsMain.objects.all().order_by('date_added')
    chem_grades = ChemMain.objects.all().order_by('date_added')
    compsci_grades = CompSciMain.objects.all().order_by('date_added')

    feedback_form = FeedbackForm()

    context = {
        "feedback_form": feedback_form,
        "math_grades": math_grades,
        "physics_grades": physics_grades,
        "chem_grades": chem_grades,
        "compsci_grades": compsci_grades,
    }
    return render(request, "home.html", context)

def math(request):
    if request.method != "POST":
        math = []
        math_grades = MathMain.objects.all().order_by('date_added')
        physics_grades = PhysicsMain.objects.all().order_by('date_added')
        chem_grades = ChemMain.objects.all().order_by('date_added')
        compsci_grades = CompSciMain.objects.all().order_by('date_added')

        for main in MathMain.objects.all().order_by('date_added'):
            math.append([main.title, base64.b64encode(bytes(main.image)).decode('utf-8'), main.id])

        feedback_form = FeedbackForm()
        math_main_form = MainsForms()
    else:
        math_main_form = MainsForms(request.POST, request.FILES)
        if math_main_form.is_valid():
            title = math_main_form.cleaned_data["title"]
            image = math_main_form.cleaned_data["image"]
            MathMain.objects.create(title=title, image=image.read())
            messages.success(request, "successfully added")
            return redirect("main:math")
        messages.success(request, "something went wrong")
        return redirect("main:math")

    context = {
        "math_grades": math_grades,
        "physics_grades": physics_grades,
        "chem_grades": chem_grades,
        "compsci_grades": compsci_grades,

        "math": math,

        "feedback_form": feedback_form,
        "math_main_form": math_main_form
    }
    return render(request, "math.html", context)

def study_math(request, id):
    if request.method != "POST":
        current_url = request.resolver_match.view_name

        math_grades = MathMain.objects.all().order_by('date_added')
        physics_grades = PhysicsMain.objects.all().order_by('date_added')
        chem_grades = ChemMain.objects.all().order_by('date_added')
        compsci_grades = CompSciMain.objects.all().order_by('date_added')
        grade = MathMain.objects.get(pk=id)

        units = grade.mathunit_set.order_by("id")
        subunits = MathSubUnit.objects.all().order_by("id")
        subs = []
        for subunit in subunits:
            if subunit.image:
                subs.append([subunit.title,
                             subunit.unit,
                             subunit.description,
                             base64.b64encode(bytes(subunit.image)).decode('utf-8'),
                             subunit.id])
            else:
                subs.append([subunit.title,
                             subunit.unit,
                             subunit.description,
                             None,
                             subunit.id])

        feedback_form = FeedbackForm()
        unit_form = MathUnitForm()
        subunit_form = MathSubUnitForm()
    else:
        if "unit" in request.POST and "subunit" not in request.POST:
            grade = MathMain.objects.get(pk=id)

            unit_form = MathUnitForm(data=request.POST)
            if unit_form.is_valid():
                new_unit = unit_form.save(commit=False)
                new_unit.id = MathUnit.objects.count() + 1
                new_unit.subject = grade
                new_unit.save()
                messages.success(request, "successfully added")
                return redirect("main:study_math", id=id)
        else:
            subunit_form = MathSubUnitForm(request.POST, request.FILES)
            if subunit_form.is_valid():
                new_subunit = subunit_form.save(commit=False)
                new_subunit.id = MathSubUnit.objects.count() + 1
                if request.FILES:
                    new_subunit.image = subunit_form.cleaned_data["image"].read()
                new_subunit.save()
                messages.success(request, "successfully added")
                return redirect("main:study_math", id=id)
        messages.error(request, "something went wrong")
        return redirect("main:study_math", id=id)

    context = {
        "math_grades": math_grades,
        "physics_grades": physics_grades,
        "chem_grades": chem_grades,
        "compsci_grades": compsci_grades,

        "grade": grade,
        "feedback_form": feedback_form,
        "unit_form": unit_form,
        "subunit_form": subunit_form,

        "units": units,
        "subunits": subs,

        "current_url": current_url
    }

    return render(request, 'study.html', context)

def test(request, subject, unit):
    u = unit.replace("%20", " ")
    s = subject.replace("%20", " ")
    if request.method != "POST":
        current_url = request.resolver_match.view_name

        math_grades = MathMain.objects.all().order_by('date_added')
        physics_grades = PhysicsMain.objects.all().order_by('date_added')
        chem_grades = ChemMain.objects.all().order_by('date_added')
        compsci_grades = CompSciMain.objects.all().order_by('date_added')

        feedback_form = FeedbackForm()
        if not MultipleChoiceQuiz.objects.filter(unit=u):
            multiple_choice_quiz_form = MultipleChoiceQuizForm(initial={"unit": u})
        else:
            multiple_choice_quiz_form = None
            quiz = MultipleChoiceQuiz.objects.get(unit=u)
            questions = list(quiz.questions.all())
            choices = list(MultipleChoiceChoice.objects.all())

            js_data = []
            for question in questions:
                a = []
                for choice in question.choices.all():
                    a.append(choice.choice)
                js_data.append({question.title: a})
            random.shuffle(js_data)
            js_data = js_data[:quiz.number_of_questions]
            # print(js_data)

        multiple_choice_question_form = MultipleChoiceQuestionForm()
        multiple_choice_choice_form = MultipleChoiceChoiceForm()
    else:
        if "quiz" in request.POST and "question" not in request.POST:
            multiple_choice_quiz_form = MultipleChoiceQuizForm(data=request.POST)
            if multiple_choice_quiz_form.is_valid():
                multiple_choice_quiz_form.save()
                messages.success(request, "successfully added")
                return redirect("main:test", subject=s , unit=u)
        elif "question" in request.POST and "choice" not in request.POST:
            multiple_choice_question_form = MultipleChoiceQuestionForm(request.POST, request.FILES)
            if multiple_choice_question_form.is_valid():
                new_question = multiple_choice_question_form.save(commit=False)
                new_question.solution = multiple_choice_question_form.cleaned_data["image"].read()
                new_question.save()
                messages.success(request, "successfully added")
                return redirect("main:test", subject=s, unit=u)
        else:
            multiple_choice_choice_form = MultipleChoiceChoiceForm(data=request.POST)
            if multiple_choice_choice_form.is_valid():
                multiple_choice_choice_form.save()
                messages.success(request, "successfully added")
                return redirect("main:test", subject=s, unit=u)
        messages.error(request, "something went wrong")
        return redirect("main:test", subject=s, unit=u)

    context = {
        "math_grades": math_grades,
        "physics_grades": physics_grades,
        "chem_grades": chem_grades,
        "compsci_grades": compsci_grades,

        "feedback_form": feedback_form,
        "multiple_choice_quiz_form": multiple_choice_quiz_form,
        "multiple_choice_question_form": multiple_choice_question_form,
        "multiple_choice_choice_form": multiple_choice_choice_form,

        "current_url": current_url,
        "unit": u,
        "subject": s
    }

    if MultipleChoiceQuiz.objects.filter(unit=u):
        context = context | {
                             'quiz':quiz,
                             'questions':questions,
                             'choices':choices,
                             'js_data': json.dumps(js_data),
                            }

    return render(request, "test.html", context)

def test_check(request, subject, unit):
    u = unit.replace("%20", " ")
    data = dict(request.POST)
    correct = False
    correct_answer = None
    for k, v in data.items():
        if k == "csrfmiddlewaretoken":
            continue
        else:
            correct_answer = MultipleChoiceQuiz.objects.get(unit=u).questions.get(title=k).choices.get(correct=True)
            if v == ['']:
                break
            answer = MultipleChoiceQuiz.objects.get(unit=u).questions.get(title=k).choices.get(choice=v[-1])
            correct = answer.correct
    return JsonResponse({"status": correct, "correct_answer": correct_answer.choice})

study_app/templates/base.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

<link rel="icon" type="images/x-icon" href="{% static 'favicon.ico' %}">
{% block header %}{% endblock header %}

<nav class="navbar sticky-top navbar-expand-lg bg-dark border-bottom border-body">
  <div class="container-fluid">
    <img src="{% static 'book.svg' %}" alt="Logo" width="50" height="50" class="d-inline-block align-text-top">
    <a class="navbar-brand text-light ms-3" href="{% url 'main:home' %}">
      <h3>
          Home |
      </h3>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon">
        <img src="{% static 'expand.png' %}" alt="exp." width="40px" height="40px">
      </span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav gap-3">
        <li class="nav-item dropdown bg-dark">
          <a class="dropdown-toggle fs-6 btn btn-outline-info text-light" href="{% url 'main:math' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <strong>
              Math
            </strong>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'main:math' %}">Math (start here)</a>
            </li>
            <li><hr class="dropdown-divider"></li>
            {% for grade in math_grades %}
            <li>
              <a class="dropdown-item" href="{% url 'main:study_math' grade.id %}">{{ grade.title }}</a>
            </li>
            {% endfor %}
          </ul>
        </li>

        <li class="nav-item dropdown bg-dark">
          <a class="dropdown-toggle fs-6 btn btn-outline-info text-light" href="{% url 'main:physics' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <strong>
              Physics
            </strong>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'main:physics' %}">Physics (start here)</a>
            </li>
            <li><hr class="dropdown-divider"></li>
            {% for grade in physics_grades %}
            <li>
              <a class="dropdown-item" href="{% url 'main:study_physics' grade.id %}">{{ grade.title }}</a>
            </li>
            {% endfor %}
          </ul>
        </li>

        <li class="nav-item dropdown bg-dark">
          <a class="dropdown-toggle fs-6 btn btn-outline-info text-light" href="{% url 'main:chemistry' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <strong>
              Chemistry
            </strong>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'main:chemistry' %}">Chemistry (start here)</a>
            </li>
            <li><hr class="dropdown-divider"></li>
            {% for grade in chem_grades %}
            <li>
              <a class="dropdown-item" href="{% url 'main:study_chemistry' grade.id %}">{{ grade.title }}</a>
            </li>
            {% endfor %}
          </ul>
        </li>

        <li class="nav-item dropdown bg-dark">
          <a class="dropdown-toggle fs-6 btn btn-outline-info text-light" href="{% url 'main:compsci' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <strong>
              Computer Science
            </strong>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'main:compsci' %}">CompSci (start here)</a>
            </li>
            <li><hr class="dropdown-divider"></li>
            {% for grade in compsci_grades %}
            <li>
              <a class="dropdown-item" href="{% url 'main:study_compsci' grade.id %}">{{ grade.title }}</a>
            </li>
            {% endfor %}
          </ul>
        </li>

        <li class="nav-item">
          <a class="btn btn-outline-info text-light fs-6" href="{% url 'main:game' %}" role="button">
            <strong>
              Dino Run
            </strong>
          </a>
        </li>
        {% if user.username == "adminguy" %}
        <li class="nav-item">
          <a class="btn btn-outline-info text-light fs-6" href="{% url 'main:feedback' %}" role="button">
            <strong>
              Feedback
            </strong>
          </a>
        </li>
        {% endif %}
      </ul>
      {% if user.is_authenticated %}
      <h5 class="text-light ms-auto greetings">
        Hello <span class="fw-bold">{{ user.username }}</span>
      </h5>
      <a class="nav-link me-1 text-light" href="{% url 'user:logout_user' %}">
        <h5>
          | Logout
        </h5>
      </a>
      {% else %}
      <a class="nav-link ms-auto text-light" href="{% url 'user:login_user' %}">
        <h5>
          Login
        </h5>
      </a>
      <h5 class="text-light">|</h5>
      <a class="nav-link text-light" href="{% url 'user:register' %}">
        <h5>
          Sign Up
        </h5>
      </a>
      {% endif %}
    </div>
  </div>
</nav>

<div class="modal fade" id="feedbackModal" tabindex="-1" aria-labelledby="GeneralModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content bg-success">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-light">Thanks for the Feedback</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-light">
        You can close this now
        <br>
        <br>
        *NOTE* All feedbacks submitted will include the username if applicable
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="GeneralModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content bg-success">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-light">You have Logged Out</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-light">
        Thank You for Visiting the Site
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="errorModal" tabindex="-1" aria-labelledby="GeneralModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content bg-danger">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-light">Something was Wrong with Your Information</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-light">
        Double check that all information provided is aligned with the requirements
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="GeneralModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content bg-success">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-light">Successfully Added</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-light">
        You can close this now
      </div>
    </div>
  </div>
</div>

{% block content %}{% endblock content %}

<footer class="bg-dark py-3 border-top">
  <div class="container-fluid">
    <form class="text-light ms-4 me-4" action="{% url 'main:add_feedback' %}" method="POST">
      <h5>Give Me Feedback!</h5>
      <br>
      <div class="d-flex flex-sm-row w-100 gap-3 text-dark">
        {% csrf_token %}
        <div class="w-100">
          {% bootstrap_form feedback_form %}
        </div>

        <button class="btn btn-info text-dark" type="submit" style="height: 40px;">
          Submit
        </button>
      </div>
    </form>
  </div>
</footer>

study_app/templates/feedback.html
<!DOCTYPE html>
{% extends './base.html' %}
{% load static %}
{% load bootstrap5 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block header %}
    <title>Give me Feedback</title>
    <link rel="stylesheet" href="{% static 'feedback.css' %}">
    {% endblock header %}
</head>
<body>
{% block content %}
<!--{% if messages %}-->
<!--<ul class="messages">-->
<!--    {% for message in messages %}-->
<!--        {% if message.tags == "success" %}-->
<!--        <li class="{{ message.tags }}">-->
<!--            <div class="text-center bg-success rounded-3 jumbotron-custom">-->
<!--                <div class="container-fluid py-3">-->
<!--                    <h3 class="display-7 fw-bold">{{ message }}</h3>-->
<!--                </div>-->
<!--            </div>-->
<!--        </li>-->
<!--        {% else %}-->
<!--        <li class="{{ message.tags }}">-->
<!--            <div class="text-center bg-danger rounded-3 jumbotron-custom">-->
<!--                <div class="container-fluid py-3">-->
<!--                    <h3 class="display-7 fw-bold">{{ message }}</h3>-->
<!--                </div>-->
<!--            </div>-->
<!--        </li>-->
<!--        {% endif %}-->
<!--    {% endfor %}-->
<!--</ul>-->
<!--{% endif %}-->

<div class="p-5 text-center mb-4 mr-4 ml-7 mt-4 bg-dark border rounded-3 jumbotron-custom" style="--bs-bg-opacity: .90;">
    <div class="container-fluid py-2">
        {% for feedback in feedbacks %}
        <div class="card bg-success mb-3">
          <div class="fs-4 card-body fw-bold text-end">
            <div class="text-center">
                {{ feedback.feedback }}
            </div>
             - {{ feedback.owner }}
            <br>
            <br>
            <a href="{% url 'main:feedback_delete' feedback.id %}" class="btn btn-danger">
                delete
            </a>
          </div>
        </div>
        {% empty %}
        <h1 class="text-light">There is no Feedback rn</h1>
        {% endfor %}
    </div>
</div>

{% endblock content %}
</body>
</html>

study_app/templates/home.html
<!DOCTYPE html>
{% extends './base.html' %}

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block header %}
    <title>Welcome</title>
    <link rel="stylesheet" href="{% static 'home.css' %}">
    {% endblock header %}
</head>
<body>
{% block content %}
<div class="p-5 text-center mb-4 mt-4 bg-dark border rounded-3 jumbotron-custom" style="--bs-bg-opacity: .90;">
    <div class="container-fluid py-2">
        <h1 class="display-5 fw-bold text-light">Welcome!</h1>
        <p class="lead text-light">
            This website is created by Edwin and it is a public archive for the stuff that will be
            taught in grades 9 to 12 for various subjects. You can review concepts from different
            grades. If you get bored or want to do something else, check out the Dino Run tab to
            play dino run (even though you can just leave this site and play it elsewhere...)! If
            you have any suggestions or comments, you can scroll down to the bottom of any page
            and write it there. Thank you!
        </p>
    </div>
</div>

<div class="row mb-5" style="margin-left: 13%; margin-right: 13%;">
  <div class="col-sm-4 mb-3">
    <div class="card bg-dark border border-1" style="--bs-border-opacity: .5;">
      <img src="{% static 'images/math.jpg' %}" class="card-img-top" alt="math">
      <div class="card-body">
        <h5 class="card-title text-light mb-5">Math</h5>
        <a href="{% url 'main:math' %}" class="btn btn-outline-info text-light fw-bold">Go</a>
      </div>
    </div>
  </div>
  <div class="col-sm-4 mb-3">
    <div class="card bg-dark border border-1" style="--bs-border-opacity: .5;">
      <img src="{% static 'images/physics.jpg' %}" class="card-img-top" alt="physics">
      <div class="card-body">
        <h5 class="card-title text-light mb-5">physics</h5>
        <a href="{% url 'main:physics' %}" class="btn btn-outline-info text-light fw-bold">Go</a>
      </div>
    </div>
  </div>
  <div class="col-sm-4 mb-3">
    <div class="card bg-dark border border-1" style="--bs-border-opacity: .5;">
      <img src="{% static 'images/chemistry.png' %}" class="card-img-top" alt="chemistry">
      <div class="card-body">
        <h5 class="card-title text-light mb-5">Chemistry</h5>
        <a href="{% url 'main:chemistry' %}" class="btn btn-outline-info text-light fw-bold">Go</a>
      </div>
    </div>
  </div>
  <div class="col-sm-4 mb-3 mb-sm-0">
    <div class="card bg-dark border border-1" style="--bs-border-opacity: .5;">
      <img src="{% static 'images/compsci.png' %}" class="card-img-top" alt="compsci">
      <div class="card-body">
        <h5 class="card-title text-light mb-5">Computer Science</h5>
        <a href="{% url 'main:compsci' %}" class="btn btn-outline-info text-light fw-bold">Go</a>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="GeneralModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content bg-success">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-light">you have logged in</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-light">
        *NOTE* There are no benefits for having an account. All information are accessible with or
        without an account
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="accountCreationModal" tabindex="-1" aria-labelledby="GeneralModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content bg-success">
      <div class="modal-header">
        <h1 class="modal-title fs-5 text-light">You have Created an Account</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-light">
        *NOTE* There are no benefits for having an account. All information are accessible with or
        without an account
      </div>
    </div>
  </div>
</div>

<script>
    {% if messages %}
        {% for message in messages %}
            {% if message.message == "Thanks for The Feedback" %}
                var myModal = new bootstrap.Modal(document.getElementById('feedbackModal'), {});
                myModal.toggle();
            {% elif message.message == "you have logged in" %}
                var myModal = new bootstrap.Modal(document.getElementById('loginModal'), {});
                myModal.toggle();
            {% elif message.message == "You have Logged Out" %}
                var myModal = new bootstrap.Modal(document.getElementById('logoutModal'), {});
                myModal.toggle();
            {% elif message.message == "you have created an account" %}
                var myModal = new bootstrap.Modal(document.getElementById('accountCreationModal'), {});
                myModal.toggle();
            {% endif %}
        {% endfor %}
    {% endif %}
</script>
{% endblock content %}
</body>
</html>